#!/usr/bin/env node
// node cli/hooks-install.js claude|opencode [--global|--project <dir>] [--json]
//
// Installs away-mode hooks into the target harness's config. MUST MERGE,
// NEVER CLOBBER — the target file may already have unrelated hooks
// (e.g. gitnexus, iterm2). Appends one entry per event, keyed on our
// own command string so re-running is idempotent.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, dirname, resolve } from 'node:path'
import { parseFlags, output } from './lib/args.js'

const [harness] = process.argv.slice(2)
const flags = parseFlags(process.argv.slice(3), ['json', 'global'])

const TSB_HOOK_MARKER = 'tsb-hook'

function claudeSettingsPath(flags) {
  if (flags.project) return join(resolve(flags.project), '.claude', 'settings.json')
  if (flags.global) return join(homedir(), '.claude', 'settings.json')
  return join(homedir(), '.claude', 'settings.json')
}

function claudeHookEntries() {
  return {
    PreToolUse: [{ matcher: '*', hooks: [{ type: 'command', command: 'tsb-hook preToolUse', timeout: 330 }] }],
    Stop: [{ hooks: [{ type: 'command', command: 'tsb-hook stop', timeout: 330 }] }],
    PreCompact: [{ matcher: 'auto', hooks: [{ type: 'command', command: 'tsb-hook preCompact', timeout: 330 }] }],
    Notification: [{ matcher: 'idle_prompt|agent_needs_input|agent_completed', hooks: [{ type: 'command', command: 'tsb-hook notification', timeout: 15 }] }],
  }
}

function isTsbEntry(entry) {
  return entry?.hooks?.some(h => typeof h.command === 'string' && h.command.includes(TSB_HOOK_MARKER))
}

function mergeClaudeHooks(existing, newEntries) {
  const merged = { ...existing }
  for (const [event, entries] of Object.entries(newEntries)) {
    const current = merged[event] || []
    const withoutOurs = current.filter(e => !isTsbEntry(e))
    merged[event] = [...withoutOurs, ...entries]
  }
  return merged
}

function installClaude() {
  const settingsPath = claudeSettingsPath(flags)
  let settings = {}
  if (existsSync(settingsPath)) {
    try { settings = JSON.parse(readFileSync(settingsPath, 'utf8')) } catch {}
  }
  const existingHooks = settings.hooks || {}
  settings.hooks = mergeClaudeHooks(existingHooks, claudeHookEntries())
  mkdirSync(dirname(settingsPath), { recursive: true })
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n')
  return { ok: true, harness: 'claude', path: settingsPath, events: Object.keys(claudeHookEntries()) }
}

function opencodePluginStub() {
  return `// Auto-generated by team-slack-bridge — do not edit
// Loads the away-mode plugin from the installed bridge package.
import { AwayModePlugin } from 'team-slack-bridge/adapters/opencode-plugin.js'
export default AwayModePlugin
`
}

function installOpencode() {
  const pluginDir = flags.project
    ? join(resolve(flags.project), '.opencode', 'plugins')
    : join(homedir(), '.config', 'opencode', 'plugins')
  mkdirSync(pluginDir, { recursive: true })
  const stubPath = join(pluginDir, 'tsb-away.mjs')
  writeFileSync(stubPath, opencodePluginStub())
  return { ok: true, harness: 'opencode', path: stubPath }
}

if (harness === 'claude') {
  output(installClaude(), { json: flags.json })
} else if (harness === 'opencode') {
  output(installOpencode(), { json: flags.json })
} else {
  console.error('usage: hooks-install.js <claude|opencode> [--global|--project <dir>] [--json]')
  process.exit(1)
}
